server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/,http://eureka-7901:7901/eureka/,http://eureka-7902:7902/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true

  instance:
    lease-renewal-interval-in-seconds: 30
spring:
  application:
    name: api-passenger

logging:
  level:
    org.springframework: debug
